import 'package:drift/drift.dart';
import 'package:flutter/foundation.dart';
import 'package:uuid/uuid.dart';
import '../app_database.dart';
import '../tables/sync_tables.dart';

part 'settings_dao.g.dart';

@DriftAccessor(tables: [AppSettings])
class SettingsDao extends DatabaseAccessor<AppDatabase>
    with _$SettingsDaoMixin {
  SettingsDao(super.db);

  Future<String?> getSetting(String key, {String? userId}) async {
    try {
      final query = select(appSettings)
        ..where((s) => s.settingKey.equals(key));
      if (userId != null) {
        query.where((s) => s.userId.equals(userId));
      } else {
        query.where((s) => s.userId.isNull());
      }
      final row = await query.getSingleOrNull();
      return row?.settingValue;
    } catch (e) {
      debugPrint('SettingsDao: Error getting setting "$key": $e');
      return null;
    }
  }

  Future<void> setSetting(String key, String value, {String? userId}) async {
    try {
      await into(appSettings).insertOnConflictUpdate(
        AppSettingsCompanion(
          userId: Value(userId),
          settingKey: Value(key),
          settingValue: Value(value),
          updatedAt: Value(DateTime.now().toUtc()),
          // ID will be generated by clientDefault if not provided on insert
          // but insertOnConflictUpdate needs a full object for the update part.
          // To be safe, we let Drift handle the unique key constraint (userId, settingKey).
        ),
      );
    } catch (e) {
      debugPrint('SettingsDao: Error setting "$key": $e');
    }
  }

  Future<bool> isDbInitialized() async {
    try {
      final val = await getSetting('db_initialized');
      return val == '1';
    } catch (_) {
      return false;
    }
  }

  Future<bool> isAdminPasswordChanged() async {
    try {
      final val = await getSetting('admin_password_changed');
      return val == '1';
    } catch (_) {
      return false;
    }
  }
}
